---
- name: Deploy application to Kubernetes
  hosts: local
  become: no  # Если не нужны права root
  vars:
    docker_image: "{{ docker_image }}"  # Переменная передается из Jenkins
  tasks:
    - name: Update Kubernetes Deployment with new image
      k8s:
        state: present
        definition:
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: my-app
            namespace: default
          spec:
            replicas: 1
            selector:
              matchLabels:
                app: my-app
            template:
              metadata:
                labels:
                  app: my-app
              spec:
                containers:
                  - name: my-app
                    image: "{{ docker_image }}"
                    ports:
                      - containerPort: 8000

    - name: Wait for deployment to complete
      k8s_rollout:
        api_version: apps/v1
        kind: Deployment
        name: my-app
        namespace: default
        wait: yes
        timeout: 300

    - name: Debug deployment status
      debug:
        msg: "Deployment updated successfully with image: {{ docker_image }}"
