---
- name: Deploy application to Kubernetes
  hosts: localhost
  connection: local
  become: no
  vars:
    docker_image: "efilimonov/back:latest"  # Можно передать извне через параметры запуска

  tasks:
    - name: Update Kubernetes Deployment with new image
      k8s:
        state: present
        definition:
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: my-app
            namespace: default
          spec:
            replicas: 1
            selector:
              matchLabels:
                app: my-app
            template:
              metadata:
                labels:
                  app: my-app
              spec:
                containers:
                  - name: my-app
                    image: "efilimonov/back:latest"  # Используем переменную
                    ports:
                      - containerPort: 8000

    - name: Wait for deployment to complete
      shell: kubectl rollout status deployment/my-app -n default --timeout=60s
      register: rollout_status
      failed_when:
        - rollout_status.rc != 0
        - "'not found' in rollout_status.stderr or 'error' in rollout_status.stderr"

    - name: Debug rollout status
      debug:
        msg: "{{ rollout_status.stdout }}"
